# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.31

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/local/bin/cmake

# The command to remove a file.
RM = /usr/local/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/runner/work/pacman.c/pacman.c

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/runner/work/pacman.c/pacman.c/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/usr/local/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/local/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/pacman.c/pacman.c/build/CMakeFiles /home/runner/work/pacman.c/pacman.c/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/runner/work/pacman.c/pacman.c/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named sokol

# Build rule for target.
sokol: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 sokol
.PHONY : sokol

# fast build rule for target.
sokol/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sokol.dir/build.make CMakeFiles/sokol.dir/build
.PHONY : sokol/fast

#=============================================================================
# Target rules for targets named pacman

# Build rule for target.
pacman: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pacman
.PHONY : pacman

# fast build rule for target.
pacman/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/build
.PHONY : pacman/fast

pacman.o: pacman.c.o
.PHONY : pacman.o

# target to build an object file
pacman.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/pacman.c.o
.PHONY : pacman.c.o

pacman.i: pacman.c.i
.PHONY : pacman.i

# target to preprocess a source file
pacman.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/pacman.c.i
.PHONY : pacman.c.i

pacman.s: pacman.c.s
.PHONY : pacman.s

# target to generate assembly for a file
pacman.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pacman.dir/build.make CMakeFiles/pacman.dir/pacman.c.s
.PHONY : pacman.c.s

sokol/sokol.o: sokol/sokol.c.o
.PHONY : sokol/sokol.o

# target to build an object file
sokol/sokol.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sokol.dir/build.make CMakeFiles/sokol.dir/sokol/sokol.c.o
.PHONY : sokol/sokol.c.o

sokol/sokol.i: sokol/sokol.c.i
.PHONY : sokol/sokol.i

# target to preprocess a source file
sokol/sokol.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sokol.dir/build.make CMakeFiles/sokol.dir/sokol/sokol.c.i
.PHONY : sokol/sokol.c.i

sokol/sokol.s: sokol/sokol.c.s
.PHONY : sokol/sokol.s

# target to generate assembly for a file
sokol/sokol.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/sokol.dir/build.make CMakeFiles/sokol.dir/sokol/sokol.c.s
.PHONY : sokol/sokol.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... pacman"
	@echo "... sokol"
	@echo "... pacman.o"
	@echo "... pacman.i"
	@echo "... pacman.s"
	@echo "... sokol/sokol.o"
	@echo "... sokol/sokol.i"
	@echo "... sokol/sokol.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

