var f;f||=typeof Module != 'undefined' ? Module : {};var aa="object"==typeof window,g="undefined"!=typeof WorkerGlobalScope,ba="object"==typeof process&&process.versions?.node&&"renderer"!=process.type,ca=[],da="./this.program",ea=(a,b)=>{throw b;},fa="undefined"!=typeof document?document.currentScript?.src:void 0;"undefined"!=typeof __filename?fa=__filename:g&&(fa=self.location.href);var ha="",ia,ja;
if(ba){var fs=require("fs");ha=__dirname+"/";ja=a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a)};ia=async a=>{a=ka(a)?new URL(a):a;return fs.readFileSync(a,void 0)};1<process.argv.length&&(da=process.argv[1].replace(/\\/g,"/"));ca=process.argv.slice(2);"undefined"!=typeof module&&(module.exports=f);ea=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||g){try{ha=(new URL(".",fa)).href}catch{}g&&(ja=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ia=async a=>{if(ka(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{200==e.status||0==e.status&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var n=console.error.bind(console),p,r=!1,la,ka=a=>a.startsWith("file://"),ma,u,v,na,oa,w,x,pa,y,A=0,B=null;
function qa(a){f.onAbort?.(a);a="Aborted("+a+")";n(a);r=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var ra;async function sa(a){if(!p)try{var b=await ia(a);return new Uint8Array(b)}catch{}if(a==ra&&p)a=new Uint8Array(p);else if(ja)a=ja(a);else throw"both async and sync fetching of the wasm failed";return a}
async function ta(a,b){try{var c=await sa(a);return await WebAssembly.instantiate(c,b)}catch(d){n(`failed to asynchronously prepare wasm: ${d}`),qa(d)}}async function ua(a){var b=ra;if(!p&&"function"==typeof WebAssembly.instantiateStreaming&&!ka(b)&&!ba)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){n(`wasm streaming compile failed: ${d}`),n("falling back to ArrayBuffer instantiation")}return ta(b,a)}
class va{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var wa=a=>{for(;0<a.length;)a.shift()(f)},xa=[],ya=[],za=()=>{var a=f.preRun.shift();ya.push(a)},Aa=!0,Ha=(a,b)=>{Ba=a;Ca=b;if(C)if(Da||=!0,0==a)D=function(){setTimeout(E,Math.max(0,Ea+b-performance.now())|0)};else if(1==a)D=function(){Fa(E)};else if(2==a){if("undefined"==typeof Ga)if("undefined"==typeof setImmediate){var c=[];addEventListener("message",d=>{if("setimmediate"===d.data||"setimmediate"===d.data.target)d.stopPropagation(),c.shift()()},!0);Ga=d=>{c.push(d);if(g){let e;(e=f).setImmediates??
(e.setImmediates=[]);f.setImmediates.push(d);postMessage({target:"setimmediate"})}else postMessage("setimmediate","*")}}else Ga=setImmediate;D=function(){Ga(E)}}},Ia=a=>{la=a;Aa||(f.onExit?.(a),r=!0);ea(a,new va(a))},Ja=a=>{la=a;Ia(a)},Ka=a=>{a instanceof va||"unwind"==a||ea(1,a)},La=()=>{if(!Aa)try{var a=la;la=a;Ia(a)}catch(b){Ka(b)}},Ua=(a,b,c,d,e)=>{function k(){return h<Ma?(La(),!1):!0}C=a;Na=d;var h=Ma;Da=!1;E=function(){if(!r)if(0<Oa.length){var l=Oa.shift();l.Zc(l.Oc);if(Pa){var m=Pa,q=0==
m%1?m-1:Math.floor(m);Pa=l.Qc?q:(8*m+(q+.5))/9}f.setStatus&&(l=f.statusMessage||"Please wait...",m=Pa??0,q=Qa.Vc??0,m?m<q?f.setStatus("{message} ({expected - remaining}/{expected})"):f.setStatus(l):f.setStatus(""));k()&&setTimeout(E,0)}else if(k())if(Ra=Ra+1|0,1==Ba&&1<Ca&&0!=Ra%Ca)D();else{0==Ba&&(Ea=performance.now());a:if(!r){for(l of Sa)if(!1===l())break a;if(!r)try{a(),La()}catch(t){Ka(t)}for(m of Ta)m()}k()&&D()}};e||(0<b?Ha(0,1E3/b):Ha(1,1),D());if(c)throw"unwind";},Da=!1,D=null,Ma=0,C=null,
Na=0,Ba=0,Ca=0,Ra=0,Oa=[],Sa=[],Ta=[];function Va(){D=null;Ma++}var F=0;function Fa(a){if("function"==typeof requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(0===F)F=b+1E3/60;else for(;b+2>=F;)F+=1E3/60;setTimeout(a,Math.max(F-b,0))}}
var Qa={},Ea,E,Ga,Pa,Wa="undefined"!=typeof TextDecoder?new TextDecoder:void 0,G=(a=0,b=NaN)=>{var c=v,d=a+b;for(b=a;c[b]&&!(b>=d);)++b;if(16<b-a&&c.buffer&&Wa)return Wa.decode(c.subarray(a,b));for(d="";a<b;){var e=c[a++];if(e&128){var k=c[a++]&63;if(192==(e&224))d+=String.fromCharCode((e&31)<<6|k);else{var h=c[a++]&63;e=224==(e&240)?(e&15)<<12|k<<6|h:(e&7)<<18|k<<12|h<<6|c[a++]&63;65536>e?d+=String.fromCharCode(e):(e-=65536,d+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else d+=String.fromCharCode(e)}return d},
Xa=[0,"undefined"!=typeof document?document:0,"undefined"!=typeof window?window:0],H=a=>{a=2<a?a?G(a):"":a;return Xa[a]||("undefined"!=typeof document?document.querySelector(a):null)},Ya=a=>0>Xa.indexOf(a)?a.getBoundingClientRect():{left:0,top:0},I;function Za(a){var b=J.Rb[a];b.target.removeEventListener(b.Qb,b.wc,b.Sb);J.Rb.splice(a,1)}function $a(){if(navigator.userActivation?navigator.userActivation.isActive:J.hc&&J.Jc.ec){var a=J.Wb;J.Wb=[];for(var b of a)b.kc(...b.sc)}}
function L(a){if(!a.target)return-4;if(a.Tb)a.wc=function(c){++J.hc;J.Jc=a;$a();a.Ub(c);$a();--J.hc},a.target.addEventListener(a.Qb,a.wc,a.Sb),J.Rb.push(a);else for(var b=0;b<J.Rb.length;++b)J.Rb[b].target==a.target&&J.Rb[b].Qb==a.Qb&&Za(b--);return 0}function ab(a){return a?a==window?"#window":a==screen?"#screen":a?.nodeName||"":""}
var J={Pc:0,$c:0,ic:0,dc:0,oc:0,mc:0,fc:0,Tc:0,ed:0,Sc:0,Yc:0,jc:0,od:0,lc:0,bd(a,b,c){u.set(u.subarray(b,b+c),a)},hd(){for(;J.Rb.length;)Za(J.Rb.length-1);J.Wb=[]},hc:0,Wb:[],Rc(a,b,c){function d(k,h){if(k.length!=h.length)return!1;for(var l in k)if(k[l]!=h[l])return!1;return!0}for(var e of J.Wb)if(e.kc==a&&d(e.sc,c))return;J.Wb.push({kc:a,Ac:b,sc:c});J.Wb.sort((k,h)=>k.Ac<h.Ac)},kd(a){J.Wb=J.Wb.filter(b=>b.kc!=a)},Rb:[],jd:(a,b)=>{for(var c=0;c<J.Rb.length;++c)J.Rb[c].target!=a||b&&b!=J.Rb[c].Qb||
Za(c--)},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},M=(a,b,c)=>{var d=v;if(!(0<c))return 0;var e=b;c=b+c-1;for(var k=0;k<a.length;++k){var h=a.codePointAt(k);if(127>=h){if(b>=c)break;d[b++]=h}else if(2047>=h){if(b+1>=c)break;d[b++]=192|h>>6;d[b++]=128|h&63}else if(65535>=h){if(b+2>=c)break;d[b++]=224|h>>12;d[b++]=128|h>>6&63;d[b++]=128|h&63}else{if(b+3>=c)break;d[b++]=240|h>>18;d[b++]=128|h>>12&63;d[b++]=128|h>>6&63;d[b++]=128|h&63;k++}}d[b]=0;return b-
e},bb=(a,b,c,d,e,k)=>{J.fc||(J.fc=N(256));a={target:H(a),Qb:k,Tb:d,Ub:(h=event)=>{var l=h.target.id?h.target.id:"",m=J.fc;M(ab(h.target),m+0,128);M(l,m+128,128);I.get(d)(e,m,b)&&h.preventDefault()},Sb:c};return L(a)},cb=(a,b,c,d,e,k)=>{J.ic||(J.ic=N(160));a={target:H(a),Qb:k,Tb:d,Ub:h=>{var l=J.ic;y[l>>3]=h.timeStamp;var m=l>>2;w[m+2]=h.location;u[l+12]=h.ctrlKey;u[l+13]=h.shiftKey;u[l+14]=h.altKey;u[l+15]=h.metaKey;u[l+16]=h.repeat;w[m+5]=h.charCode;w[m+6]=h.keyCode;w[m+7]=h.which;M(h.key||"",l+
32,32);M(h.code||"",l+64,32);M(h.char||"",l+96,32);M(h.locale||"",l+128,32);I.get(d)(e,l,b)&&h.preventDefault()},Sb:c};return L(a)},db=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;w[d+2]=b.screenX;w[d+3]=b.screenY;w[d+4]=b.clientX;w[d+5]=b.clientY;u[a+24]=b.ctrlKey;u[a+25]=b.shiftKey;u[a+26]=b.altKey;u[a+27]=b.metaKey;na[2*d+14]=b.button;na[2*d+15]=b.buttons;w[d+8]=b.movementX;w[d+9]=b.movementY;a=Ya(c);w[d+10]=b.clientX-(a.left|0);w[d+11]=b.clientY-(a.top|0)},O=(a,b,c,d,e,k)=>{J.dc||(J.dc=N(64));a=H(a);
return L({target:a,ec:"mousemove"!=k&&"mouseenter"!=k&&"mouseleave"!=k,Qb:k,Tb:d,Ub:(h=event)=>{db(J.dc,h,a);I.get(d)(e,J.dc,b)&&h.preventDefault()},Sb:c})},eb=(a,b,c,d,e)=>{J.jc||(J.jc=N(257));return L({target:a,Qb:e,Tb:d,Ub:(k=event)=>{var h=J.jc,l=document.pointerLockElement||document.Zb||document.rc||document.qc;u[h]=!!l;var m=l?.id||"";M(ab(l),h+1,128);M(m,h+129,128);I.get(d)(20,h,b)&&k.preventDefault()},Sb:c})},fb=(a,b,c,d,e)=>L({target:a,Qb:e,Tb:d,Ub:(k=event)=>{I.get(d)(38,0,b)&&k.preventDefault()},
Sb:c}),gb=(a,b,c,d)=>{J.mc||(J.mc=N(36));a=H(a);return L({target:a,Qb:"resize",Tb:d,Ub:(e=event)=>{if(e.target==a){var k=document.body;if(k){var h=J.mc;w[h>>2]=0;w[h+4>>2]=k.clientWidth;w[h+8>>2]=k.clientHeight;w[h+12>>2]=innerWidth;w[h+16>>2]=innerHeight;w[h+20>>2]=outerWidth;w[h+24>>2]=outerHeight;w[h+28>>2]=pageXOffset|0;w[h+32>>2]=pageYOffset|0;I.get(d)(10,h,b)&&e.preventDefault()}}},Sb:c})},hb=(a,b,c,d,e,k)=>{J.lc||(J.lc=N(1552));a=H(a);return L({target:a,ec:"touchstart"==k||"touchend"==k,Qb:k,
Tb:d,Ub:h=>{var l={},m=h.touches;for(var q of m)q.xc=q.zc=0,l[q.identifier]=q;for(var t of h.changedTouches)t.xc=1,l[t.identifier]=t;for(var K of h.targetTouches)l[K.identifier].zc=1;m=J.lc;y[m>>3]=h.timeStamp;u[m+12]=h.ctrlKey;u[m+13]=h.shiftKey;u[m+14]=h.altKey;u[m+15]=h.metaKey;q=m+16;t=Ya(a);K=0;for(let z of Object.values(l))if(l=q>>2,w[l]=z.identifier,w[l+1]=z.screenX,w[l+2]=z.screenY,w[l+3]=z.clientX,w[l+4]=z.clientY,w[l+5]=z.pageX,w[l+6]=z.pageY,u[q+28]=z.xc,u[q+29]=z.zc,w[l+8]=z.clientX-(t.left|
0),w[l+9]=z.clientY-(t.top|0),q+=48,31<++K)break;w[m+8>>2]=K;I.get(d)(e,m,b)&&h.preventDefault()},Sb:c})},P,ib=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,k)=>b.drawArraysInstancedANGLE(c,d,e,k),a.drawElementsInstanced=(c,d,e,k,h)=>b.drawElementsInstancedANGLE(c,d,e,k,h))},jb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=
c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},kb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},lb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return(a.getSupportedExtensions()||[]).filter(c=>b.includes(c))},mb=1,Q=[],R=[],nb=[],S=[],T=[],U=[],ob=[],pb=[],V=[],qb={},rb=4,sb=0,tb=a=>{for(var b=mb++,c=a.length;c<b;c++)a[c]=null;return b},X=(a,b,c,d)=>{for(var e=0;e<a;e++){var k=P[c](),h=k&&tb(d);k?(k.name=h,d[h]=k):W||=1282;w[b+4*e>>2]=h}},vb=(a,b)=>{a.Zb||(a.Zb=a.getContext,a.getContext=function(d,e){e=a.Zb(d,e);return"webgl"==d==e instanceof WebGLRenderingContext?e:null});var c=1<b.yc?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
ub(c,b):0},ub=(a,b)=>{var c=tb(pb),d={handle:c,attributes:b,version:b.yc,pc:a};a.canvas&&(a.canvas.Nc=d);pb[c]=d;("undefined"==typeof b.vc||b.vc)&&wb(d);return c},wb=a=>{a||=Y;if(!a.Mc){a.Mc=!0;var b=a.pc;b.dd=b.getExtension("WEBGL_multi_draw");b.Xc=b.getExtension("EXT_polygon_offset_clamp");b.Wc=b.getExtension("EXT_clip_control");b.pd=b.getExtension("WEBGL_polygon_mode");ib(b);jb(b);kb(b);b.Uc=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.ad=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
2<=a.version&&(b.uc=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(2>a.version||!b.uc)b.uc=b.getExtension("EXT_disjoint_timer_query");lb(b).forEach(c=>{c.includes("lose_context")||c.includes("debug")||b.getExtension(c)})}},W,Y,xb=(a,b,c,d,e,k)=>{a={target:H(a),Qb:k,Tb:d,Ub:(h=event)=>{I.get(d)(e,0,b)&&h.preventDefault()},Sb:c};L(a)},yb=(a,b,c,d)=>{J.oc||(J.oc=N(96));return L({target:a,ec:!0,Qb:"wheel",Tb:d,Ub:(e=event)=>{var k=J.oc;db(k,e,a);y[k+64>>3]=e.deltaX;y[k+72>>3]=e.deltaY;y[k+80>>
3]=e.deltaZ;w[k+88>>2]=e.deltaMode;I.get(d)(9,k,b)&&e.preventDefault()},Sb:c})},zb=["default","low-power","high-performance"],Ab=[],Bb=()=>{var a=lb(P);return a=a.concat(a.map(b=>"GL_"+b))},Cb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=P.getParameter(34467);c=d?d.length:0;break;case 33309:if(2>Y.version){W||=1282;return}c=Bb().length;break;case 33307:case 33308:if(2>Y.version){W||=1280;return}c=33307==a?3:0}if(void 0===
c)switch(d=P.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":W||=1280;return;case "object":if(null===d)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:W||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=
0;a<d.length;++a)w[b+4*a>>2]=d[a];return}try{c=d.name|0}catch(e){W||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:W||=1280;n(`GL_INVALID_ENUM in glGet${0}v: Native code calling glGet${0}v(${a}) and it returns ${d} of type ${typeof d}!`);return}w[b>>2]=c}else W||=1281},Db=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);127>=d?b++:2047>=d?b+=2:55296<=d&&57343>=d?(b+=4,++c):b+=3}return b},Eb=a=>{var b=Db(a)+
1,c=N(b);c&&M(a,c,b);return c},Fb=a=>"]"==a.slice(-1)&&a.lastIndexOf("["),Gb=a=>{a-=5120;return 0==a?u:1==a?v:2==a?na:4==a?w:6==a?pa:5==a||28922==a||28520==a||30779==a||30782==a?x:oa},Ib=a=>{var b=Db(a)+1,c=Hb(b);M(a,c,b);return c},Lb=a=>{var b=Jb();a();Kb(b)};f.requestAnimationFrame=Fa;f.pauseMainLoop=Va;f.resumeMainLoop=function(){Ma++;var a=Ba,b=Ca,c=C;C=null;Ua(c,0,!1,Na,!0);Ha(a,b);D()};f.preMainLoop&&Sa.push(f.preMainLoop);f.postMainLoop&&Ta.push(f.postMainLoop);for(let a=0;32>a;++a)Ab.push(Array(a));
f.noExitRuntime&&(Aa=f.noExitRuntime);f.printErr&&(n=f.printErr);f.wasmBinary&&(p=f.wasmBinary);f.arguments&&(ca=f.arguments);f.thisProgram&&(da=f.thisProgram);
var Mb,Nb,Ob,Pb,Qb,Rb,Sb,N,Kb,Hb,Jb,Tb={ab:()=>qa(""),mb:()=>{Va();C=null},P:()=>"number"==typeof devicePixelRatio&&devicePixelRatio||1,ka:(a,b,c)=>{a=H(a);if(!a)return-4;a=Ya(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},nb:()=>performance.now(),Wa:(a,b)=>{function c(d){I.get(a)(d,b)&&requestAnimationFrame(c)}return requestAnimationFrame(c)},$a:()=>{qa("OOM")},S:(a,b,c,d)=>bb(a,b,c,d,12,"blur"),N:(a,b,c)=>{a=H(a);if(!a)return-4;a.width=b;a.height=c;return 0},T:(a,b,c,d)=>bb(a,b,c,d,13,"focus"),ba:(a,
b,c,d)=>cb(a,b,c,d,2,"keydown"),$:(a,b,c,d)=>cb(a,b,c,d,1,"keypress"),aa:(a,b,c,d)=>cb(a,b,c,d,3,"keyup"),Xa:(a,b,c)=>{a=I.get(a);Ua(a,b,c)},B:(a,b,c,d)=>O(a,b,c,d,5,"mousedown"),ha:(a,b,c,d)=>O(a,b,c,d,33,"mouseenter"),fa:(a,b,c,d)=>O(a,b,c,d,34,"mouseleave"),ja:(a,b,c,d)=>O(a,b,c,d,8,"mousemove"),x:(a,b,c,d)=>O(a,b,c,d,6,"mouseup"),V:(a,b,c,d)=>{if(!document||!document.body||!(document.body.requestPointerLock||document.body.Zb||document.body.rc||document.body.qc))return-1;a=H(a);if(!a)return-4;
eb(a,b,c,d,"mozpointerlockchange");eb(a,b,c,d,"webkitpointerlockchange");eb(a,b,c,d,"mspointerlockchange");return eb(a,b,c,d,"pointerlockchange")},U:(a,b,c,d)=>{if(!document||!(document.body.requestPointerLock||document.body.Zb||document.body.rc||document.body.qc))return-1;a=H(a);if(!a)return-4;fb(a,b,c,d,"mozpointerlockerror");fb(a,b,c,d,"webkitpointerlockerror");fb(a,b,c,d,"mspointerlockerror");return fb(a,b,c,d,"pointerlockerror")},X:(a,b,c,d)=>gb(a,b,c,d),W:(a,b,c,d)=>hb(a,b,c,d,25,"touchcancel"),
Y:(a,b,c,d)=>hb(a,b,c,d,23,"touchend"),Z:(a,b,c,d)=>hb(a,b,c,d,24,"touchmove"),_:(a,b,c,d)=>hb(a,b,c,d,22,"touchstart"),R:(a,b,c,d)=>{xb(a,b,c,d,31,"webglcontextlost");return 0},Q:(a,b,c,d)=>{xb(a,b,c,d,32,"webglcontextrestored");return 0},da:(a,b,c,d)=>(a=H(a))?"undefined"!=typeof a.onwheel?yb(a,b,c,d):-1:-4,Ia:(a,b)=>{var c=b>>2;b={alpha:!!u[b+0],depth:!!u[b+1],stencil:!!u[b+2],antialias:!!u[b+3],premultipliedAlpha:!!u[b+4],preserveDrawingBuffer:!!u[b+5],powerPreference:zb[w[c+2]],failIfMajorPerformanceCaveat:!!u[b+
12],yc:w[c+4],cd:w[c+5],vc:u[b+24],Lc:u[b+25],gd:w[c+7],ld:u[b+32]};a=H(a);return!a||b.Lc?0:vb(a,b)},ya:a=>{Y=pb[a];f.ctx=P=Y?.pc;return!a||P?0:-5},r:a=>P.activeTexture(a),p:(a,b)=>{P.attachShader(R[a],U[b])},b:(a,b)=>{35051==a?P.tc=b:35052==a&&(P.Yb=b);P.bindBuffer(a,Q[b])},l:(a,b,c)=>{P.bindBufferBase(a,b,Q[c])},f:(a,b)=>{P.bindFramebuffer(a,nb[b])},Ja:(a,b)=>{P.bindRenderbuffer(a,S[b])},q:(a,b)=>{P.bindSampler(a,V[b])},g:(a,b)=>{P.bindTexture(a,T[b])},O:a=>{P.bindVertexArray(ob[a])},v:(a,b,c,d)=>
P.blendColor(a,b,c,d),w:(a,b)=>P.blendEquationSeparate(a,b),y:(a,b,c,d)=>P.blendFuncSeparate(a,b,c,d),tb:(a,b,c,d,e,k,h,l,m,q)=>P.blitFramebuffer(a,b,c,d,e,k,h,l,m,q),La:(a,b,c,d)=>{2<=Y.version?c&&b?P.bufferData(a,v,d,c,b):P.bufferData(a,b,d):P.bufferData(a,c?v.subarray(c,c+b):b,d)},L:(a,b,c,d)=>{2<=Y.version?c&&P.bufferSubData(a,b,v,d,c):P.bufferSubData(a,b,v.subarray(d,d+c))},E:a=>P.checkFramebufferStatus(a),sa:(a,b,c,d)=>P.clearBufferfi(a,b,c,d),A:(a,b,c)=>{P.clearBufferfv(a,b,pa,c>>2)},ra:(a,
b,c)=>{P.clearBufferiv(a,b,w,c>>2)},i:(a,b,c,d)=>{P.colorMask(!!a,!!b,!!c,!!d)},db:a=>{P.compileShader(U[a])},Da:(a,b,c,d,e,k,h,l,m)=>{2<=Y.version?P.Yb||!l?P.compressedTexSubImage2D(a,b,c,d,e,k,h,l,m):P.compressedTexSubImage2D(a,b,c,d,e,k,h,v,m,l):P.compressedTexSubImage2D(a,b,c,d,e,k,h,v.subarray(m,m+l))},Ba:(a,b,c,d,e,k,h,l,m,q,t)=>{P.Yb?P.compressedTexSubImage3D(a,b,c,d,e,k,h,l,m,q,t):P.compressedTexSubImage3D(a,b,c,d,e,k,h,l,m,v,t,q)},xa:()=>{var a=tb(R),b=P.createProgram();b.name=a;b.cc=b.ac=
b.bc=0;b.nc=1;R[a]=b;return a},fb:a=>{var b=tb(U);U[b]=P.createShader(a);return b},u:a=>P.cullFace(a),gb:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=Q[d];e&&(P.deleteBuffer(e),e.name=0,Q[d]=null,d==P.tc&&(P.tc=0),d==P.Yb&&(P.Yb=0))}},M:(a,b)=>{for(var c=0;c<a;++c){var d=w[b+4*c>>2],e=nb[d];e&&(P.deleteFramebuffer(e),e.name=0,nb[d]=null)}},j:a=>{if(a){var b=R[a];b?(P.deleteProgram(b),b.name=0,R[a]=null):W||=1281}},Pa:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=S[d];e&&(P.deleteRenderbuffer(e),
e.name=0,S[d]=null)}},Oa:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=V[d];e&&(P.deleteSampler(e),e.name=0,V[d]=null)}},h:a=>{if(a){var b=U[a];b?(P.deleteShader(b),U[a]=null):W||=1281}},Qa:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2],e=T[d];e&&(P.deleteTexture(e),e.name=0,T[d]=null)}},Na:(a,b)=>{for(var c=0;c<a;c++){var d=w[b+4*c>>2];P.deleteVertexArray(ob[d]);ob[d]=null}},n:a=>P.depthFunc(a),o:a=>{P.depthMask(!!a)},c:a=>P.disable(a),ia:a=>{P.disableVertexAttribArray(a)},vb:(a,b,c)=>{P.drawArrays(a,
b,c)},wb:(a,b,c,d)=>{P.drawArraysInstanced(a,b,c,d)},D:(a,b)=>{for(var c=Ab[a],d=0;d<a;d++)c[d]=w[b+4*d>>2];P.drawBuffers(c)},yb:(a,b,c,d)=>{P.drawElements(a,b,c,d)},xb:(a,b,c,d,e)=>{P.drawElementsInstanced(a,b,c,d,e)},e:a=>P.enable(a),la:a=>{P.enableVertexAttribArray(a)},F:(a,b,c,d)=>{P.framebufferRenderbuffer(a,b,c,S[d])},ca:(a,b,c,d,e)=>{P.framebufferTexture2D(a,b,c,T[d],e)},bb:(a,b,c,d,e)=>{P.framebufferTextureLayer(a,b,T[c],d,e)},t:a=>P.frontFace(a),Ma:(a,b)=>{X(a,b,"createBuffer",Q)},G:(a,b)=>
{X(a,b,"createFramebuffer",nb)},Ka:(a,b)=>{X(a,b,"createRenderbuffer",S)},za:(a,b)=>{X(a,b,"createSampler",V)},Ga:(a,b)=>{X(a,b,"createTexture",T)},Sa:(a,b)=>{X(a,b,"createVertexArray",ob)},ua:(a,b)=>P.getAttribLocation(R[a],b?G(b):""),a:(a,b)=>Cb(a,b),wa:(a,b,c,d)=>{a=P.getProgramInfoLog(R[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(w[c>>2]=b)},I:(a,b,c)=>{if(c)if(a>=mb)W||=1281;else if(a=R[a],35716==b)a=P.getProgramInfoLog(a),null===a&&(a="(unknown error)"),w[c>>2]=a.length+1;else if(35719==
b){if(!a.cc){var d=P.getProgramParameter(a,35718);for(b=0;b<d;++b)a.cc=Math.max(a.cc,P.getActiveUniform(a,b).name.length+1)}w[c>>2]=a.cc}else if(35722==b){if(!a.ac)for(d=P.getProgramParameter(a,35721),b=0;b<d;++b)a.ac=Math.max(a.ac,P.getActiveAttrib(a,b).name.length+1);w[c>>2]=a.ac}else if(35381==b){if(!a.bc)for(d=P.getProgramParameter(a,35382),b=0;b<d;++b)a.bc=Math.max(a.bc,P.getActiveUniformBlockName(a,b).length+1);w[c>>2]=a.bc}else w[c>>2]=P.getProgramParameter(a,b);else W||=1281},cb:(a,b,c,d)=>
{a=P.getShaderInfoLog(U[a]);null===a&&(a="(unknown error)");b=0<b&&d?M(a,d,b):0;c&&(w[c>>2]=b)},ea:(a,b,c)=>{c?35716==b?(a=P.getShaderInfoLog(U[a]),null===a&&(a="(unknown error)"),w[c>>2]=a?a.length+1:0):35720==b?(a=P.getShaderSource(U[a]),w[c>>2]=a?a.length+1:0):w[c>>2]=P.getShaderParameter(U[a],b):W||=1281},Ta:(a,b)=>{if(2>Y.version)return W||=1282,0;var c=qb[a];if(c)return 0>b||b>=c.length?(W||=1281,0):c[b];switch(a){case 7939:return c=Bb().map(Eb),c=qb[a]=c,0>b||b>=c.length?(W||=1281,0):c[b];
default:return W||=1280,0}},H:(a,b)=>{b=b?G(b):"";if(a=R[a]){var c=a,d=c.$b,e=c.Ic,k;if(!d){c.$b=d={};c.Hc={};var h=P.getProgramParameter(c,35718);for(k=0;k<h;++k){var l=P.getActiveUniform(c,k);var m=l.name;l=l.size;var q=Fb(m);q=0<q?m.slice(0,q):m;var t=c.nc;c.nc+=l;e[q]=[l,t];for(m=0;m<l;++m)d[t]=m,c.Hc[t++]=q}}c=a.$b;d=0;e=b;k=Fb(b);0<k&&(d=parseInt(b.slice(k+1))>>>0,e=b.slice(0,k));if((e=a.Ic[e])&&d<e[0]&&(d+=e[1],c[d]=c[d]||P.getUniformLocation(a,b)))return d}else W||=1281;return-1},sb:(a,b,
c)=>{for(var d=Ab[b],e=0;e<b;e++)d[e]=w[c+4*e>>2];P.invalidateFramebuffer(a,d)},J:a=>{a=R[a];P.linkProgram(a);a.$b=0;a.Ic={}},Ra:(a,b)=>{3317==a?rb=b:3314==a&&(sb=b);P.pixelStorei(a,b)},z:(a,b)=>P.polygonOffset(a,b),ub:a=>P.readBuffer(a),Ha:(a,b,c,d,e)=>P.renderbufferStorageMultisample(a,b,c,d,e),K:(a,b,c)=>{P.samplerParameterf(V[a],b,c)},d:(a,b,c)=>{P.samplerParameteri(V[a],b,c)},ta:(a,b,c,d)=>P.scissor(a,b,c,d),eb:(a,b,c,d)=>{for(var e="",k=0;k<b;++k){var h=(h=x[c+4*k>>2])?G(h,d?x[d+4*k>>2]:void 0):
"";e+=h}P.shaderSource(U[a],e)},ib:(a,b,c)=>P.stencilFunc(a,b,c),qa:(a,b,c,d)=>P.stencilFuncSeparate(a,b,c,d),m:a=>P.stencilMask(a),hb:(a,b,c)=>P.stencilOp(a,b,c),pa:(a,b,c,d)=>P.stencilOpSeparate(a,b,c,d),Fa:(a,b,c,d,e)=>P.texStorage2D(a,b,c,d,e),Ea:(a,b,c,d,e,k)=>P.texStorage3D(a,b,c,d,e,k),Ca:(a,b,c,d,e,k,h,l,m)=>{if(2<=Y.version){if(P.Yb){P.texSubImage2D(a,b,c,d,e,k,h,l,m);return}if(m){var q=Gb(l);P.texSubImage2D(a,b,c,d,e,k,h,l,q,m>>>31-Math.clz32(q.BYTES_PER_ELEMENT));return}}if(m){q=Gb(l);
var t=k*((sb||e)*({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[h-6402]||1)*q.BYTES_PER_ELEMENT+rb-1&-rb);m=q.subarray(m>>>31-Math.clz32(q.BYTES_PER_ELEMENT),m+t>>>31-Math.clz32(q.BYTES_PER_ELEMENT))}else m=null;P.texSubImage2D(a,b,c,d,e,k,h,l,m)},Aa:(a,b,c,d,e,k,h,l,m,q,t)=>{if(P.Yb)P.texSubImage3D(a,b,c,d,e,k,h,l,m,q,t);else if(t){var K=Gb(q);P.texSubImage3D(a,b,c,d,e,k,h,l,m,q,K,t>>>31-Math.clz32(K.BYTES_PER_ELEMENT))}else P.texSubImage3D(a,b,c,d,e,k,h,l,m,q,null)},va:(a,b)=>{var c=
P,d=c.uniform1i;var e=P.Kc;if(e){var k=e.$b[a];"number"==typeof k&&(e.$b[a]=k=P.getUniformLocation(e,e.Hc[a]+(0<k?`[${k}]`:"")));a=k}else W||=1282,a=void 0;d.call(c,a,b)},k:a=>{a=R[a];P.useProgram(a);P.Kc=a},ma:(a,b)=>{P.vertexAttribDivisor(a,b)},na:(a,b,c,d,e)=>{P.vertexAttribIPointer(a,b,c,d,e)},oa:(a,b,c,d,e,k)=>{P.vertexAttribPointer(a,b,c,!!d,e,k)},C:(a,b,c,d)=>P.viewport(a,b,c,d),_a:function(){f.Bc=a=>{0!=Nb()&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",f.Bc)},
Za:function(){f.Gc=a=>{const b=a.clipboardData.getData("text");Lb(()=>{const c=Ib(b);Mb(c)})};window.addEventListener("paste",f.Gc)},Ya:function(){f.md=[];f.Cc=b=>{b.stopPropagation();b.preventDefault()};f.Dc=b=>{b.stopPropagation();b.preventDefault()};f.Ec=b=>{b.stopPropagation();b.preventDefault()};f.Fc=b=>{b.stopPropagation();b.preventDefault();const c=b.dataTransfer.files;f.nd=c;Ob(c.length);for(let e=0;e<c.length;e++)Lb(()=>{const k=Ib(c[e].name);Pb(e,k)});let d=0;b.shiftKey&&(d|=1);b.ctrlKey&&
(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);Qb(b.clientX,b.clientY,d)};const a=f.Xb;a.addEventListener("dragenter",f.Cc,!1);a.addEventListener("dragleave",f.Dc,!1);a.addEventListener("dragover",f.Ec,!1);a.addEventListener("drop",f.Fc,!1)},Va:function(){const a=document.getElementById("sokol-app-favicon");a&&document.head.removeChild(a)},zb:function(a,b){0!==b&&(document.title=b?G(b):"");a=a?G(a):"";void 0!==f.canvas&&("object"===typeof f.canvas?Xa[a]=f.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));
f.Xb=H(a);f.Xb||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);f.Xb.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},lb:function(){window.removeEventListener("beforeunload",f.Bc)},kb:function(){window.removeEventListener("paste",f.Gc)},jb:function(){const a=f.Xb;a.removeEventListener("dragenter",f.Cc);a.removeEventListener("dragleave",f.Dc);a.removeEventListener("dragover",f.Ec);a.removeEventListener("drop",f.Fc)},s:function(){f.Xb&&
f.Xb.requestPointerLock&&f.Xb.requestPointerLock()},Ua:function(a,b,c){const d=document.createElement("canvas");d.width=a;d.height=b;const e=d.getContext("2d"),k=e.createImageData(a,b);k.data.set(v.subarray(c,c+a*b*4));e.putImageData(k,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},pb:function(){return f.Vb?f.Vb.bufferSize:0},rb:function(a,b,c){f.Pb=null;f.Vb=null;"undefined"!==typeof AudioContext?f.Pb=new AudioContext({sampleRate:a,
latencyHint:"interactive"}):(f.Pb=null,console.log("sokol_audio.h: no WebAudio support"));return f.Pb?(console.log("sokol_audio.h: sample rate ",f.Pb.sampleRate),f.Vb=f.Pb.createScriptProcessor(c,0,b),f.Vb.onaudioprocess=d=>{const e=d.outputBuffer.length,k=Sb(e);if(k){const h=d.outputBuffer.numberOfChannels;for(let l=0;l<h;l++){const m=d.outputBuffer.getChannelData(l);for(let q=0;q<e;q++)m[q]=pa[(k>>2)+(h*q+l)]}}},f.Vb.connect(f.Pb.destination),a=()=>{f.Pb&&"suspended"===f.Pb.state&&f.Pb.resume()},
document.addEventListener("click",a,{once:!0}),document.addEventListener("touchend",a,{once:!0}),document.addEventListener("keydown",a,{once:!0}),1):0},qb:function(){return f.Pb?f.Pb.sampleRate:0},ob:function(){const a=f.Pb;null!==a&&(f.Vb&&f.Vb.disconnect(),a.close(),f.Pb=null,f.Vb=null)},ga:function(a,b){b=b?G(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}},Z;
(async function(){function a(c){Z=c.exports;ma=Z.Ab;c=ma.buffer;u=new Int8Array(c);na=new Int16Array(c);v=new Uint8Array(c);oa=new Uint16Array(c);w=new Int32Array(c);x=new Uint32Array(c);pa=new Float32Array(c);y=new Float64Array(c);new BigInt64Array(c);new BigUint64Array(c);I=Z.Cb;c=Z;f.__sapp_emsc_onpaste=Mb=c.Db;f.__sapp_html5_get_ask_leave_site=Nb=c.Eb;f.__sapp_emsc_begin_drop=Ob=c.Fb;f.__sapp_emsc_drop=Pb=c.Gb;f.__sapp_emsc_end_drop=Qb=c.Hb;f.__sapp_emsc_invoke_fetch_cb=c.Ib;f._main=Rb=c.Jb;f.__saudio_emsc_pull=
Sb=c.Kb;N=c.Lb;Kb=c.Mb;Hb=c.Nb;Jb=c.Ob;A--;f.monitorRunDependencies?.(A);0==A&&B&&(c=B,B=null,c());return Z}A++;f.monitorRunDependencies?.(A);var b={a:Tb};if(f.instantiateWasm)return new Promise(c=>{f.instantiateWasm(b,(d,e)=>{c(a(d,e))})});ra??=f.locateFile?f.locateFile("pacman.wasm",ha):ha+"pacman.wasm";return a((await ua(b)).instance)})();
function Ub(a=[]){var b=Rb;a.unshift(da);var c=a.length,d=Hb(4*(c+1)),e=d;a.forEach(h=>{x[e>>2]=Ib(h);e+=4});x[e>>2]=0;try{var k=b(c,d);Ja(k)}catch(h){Ka(h)}}
function Vb(a=ca){function b(){f.calledRun=!0;if(!r){Z.Bb();f.onRuntimeInitialized?.();f.noInitialRun||Ub(a);if(f.postRun)for("function"==typeof f.postRun&&(f.postRun=[f.postRun]);f.postRun.length;){var c=f.postRun.shift();xa.push(c)}wa(xa)}}if(0<A)B=Vb;else{if(f.preRun)for("function"==typeof f.preRun&&(f.preRun=[f.preRun]);f.preRun.length;)za();wa(ya);0<A?B=Vb:f.setStatus?(f.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>f.setStatus(""),1);b()},1)):b()}}
if(f.preInit)for("function"==typeof f.preInit&&(f.preInit=[f.preInit]);0<f.preInit.length;)f.preInit.shift()();Vb();
