name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Setup Emscripten
      uses: mymindstorm/setup-emsdk@v13
      
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y mesa-common-dev libx11-dev libasound2-dev libxi-dev libxcursor-dev
      
    - name: Create build directory
      run: mkdir -p build
      
    - name: Configure with CMake
      run: |
        cd build
        emcmake cmake -G"Unix Makefiles" -DCMAKE_BUILD_TYPE=MinSizeRel ..
        
    - name: Build
      run: |
        cd build
        cmake --build .
        
    - name: Deploy to GitHub Pages
      if: github.ref == 'refs/heads/main'
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./build
        publish_branch: gh-pages
        force_orphan: true 